### ISSUE TITLE
automate release process

### ISSUE THREAD

**Issue by andrewharvey** [ideditor/imagery-index#2]
My hope is that changes made in the imagery-index can be released to users of the index immediately after the change is merged. To target this kind of release cadence, I think it would be easier to automate the release steps https://github.com/ideditor/imagery-index/blob/master/RELEASE.md as much as possible, such that you can make a small release PR and when merged the pipeline will do most of the release items for you.

**Comment by bhousel** [comment]
I'm strongly against this.

**Comment by bhousel** [comment]
I guess I should elaborate.. 

- Having a human in the loop insulates the downstream apps from breakage (which always happens sometimes) or deliberate abuse (someone deletes or changes a file because they are mad).  
- I maintain a lot of little projects like this, and I always feel like the release checklist is important for making sure I'm not forgetting anything.  
- Tagging releases and writing release notes is valuable.
- Semantic versioning can communicate how much impact a change causes, and a human should decide this.
- The steps take like a minute to run.

**Comment by andrewharvey** [comment]
Maybe I wasn't clear, I'm still okay with having a human in the loop to do the release via a PR but the actual npm publish, git tag etc and other automated processes be run on Travis automatically when the PR is merged.

This means anyone can do a release very easy and quickly.

The cadence I'm looking for is basically a release for every set of merged PRs with a source change (at most once a day will do), is that the kind of cadence okay?

**Comment by bhousel** [comment]
I would still prefer for a release to be a _decision point_ where someone decides when and whether to do the release.  

There have been plenty of times when we are waiting for just one more thing, whether it's a source that someone promised to add, or a bunch of translations that someone is working on.  Or a maintainer merges a PR and then someone else realizes it impacts them.  

I'm very much against having release steps all happen automatically just because someone merged something.  The goal here is stability, not speed.

> This means anyone can do a release very easy and quickly.

The steps in [RELEASE.md](https://github.com/ideditor/imagery-index/blob/master/RELEASE.md) are very easy and quick.  I'll grant you maintainer permission if you want it.

> The cadence I'm looking for is basically a release for every set of merged PRs with a source change (at most once a day will do), is that the kind of cadence okay?

I'd feel a bit more comfortable with a "few days to once a week" release cadence, but we could push out stuff at any time if it's urgent.  

Also I think we should write actual release notes in the CHANGELOG, and this takes a bit of time (maybe an hour or so).  Compare to the sort of thing I do in [osm-community-index](https://github.com/osmlab/osm-community-index/blob/master/CHANGELOG.md) and I think it works well.

**Comment by andrewharvey** [comment]
> I would still prefer for a release to be a decision point where someone decides when and whether to do the release.

Sure, under what I'm proposing here the release would still be a decision point as you'd need to make a release PR and merge it for the release to happen.

> There have been plenty of times when we are waiting for just one more thing, whether it's a source that someone promised to add, or a bunch of translations that someone is working on. Or a maintainer merges a PR and then someone else realizes it impacts them.

Absolutely so under this proposal, you could still hold off for a release until after tested or after a few related PRs are merged.

> I'm very much against having release steps all happen automatically just because someone merged something. The goal here is stability, not speed.

The goal of my request here is to make the release process easier and faster, while still retaining the fact that it's done manually my a maintainer.

I'm not proposing having a release happen automatically on each commit, but just have the release steps automated by Travis or some other CI tool.

**Comment by andrewharvey** [comment]
https://community.algolia.com/shipjs/ sounds like a good option

**Comment by bhousel** [comment]
Thanks @andrewharvey I did take a look at the [shipjs guide](https://community.algolia.com/shipjs/guide/).

One thing I noticed, it seems to assign the version based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), and I really don't want to force everyone contributing to write their commit messages a certain way.  Ideally we aren't really bumping versions ever, so this might not matter.

Anyway, I'm definitely willing to give it a try..

**Comment by bhousel** [comment]
I commented more on the iD side about why I'm being such a pain about this:
https://github.com/openstreetmap/iD/issues/7425#issuecomment-599132100

>But we can't do that unless all the software we depend on follows a predictable release process with semantic version numbers. The files we fetch must be compatible with the code we've written to process them.
>
>ELI shouldn't just add or remove properties from their distributed files on a whim. Even as recent as last week, ELI still has issues where the robot script deleted files because someone accepted a PR too quickly
>
>Stuff like that can break iD for thousands of users and impact scheduled events like mapathons. So I stand by my decision to not fetch the current imagery.json file from the main branch of the ELI repository and this is why I am being so insistent about following a release checklist, writing a changelog, and publishing software with semantic version numbers.

**Comment by andrewharvey** [comment]
> One thing I noticed, it seems to assign the version based on conventional commits, and I really don't want to force everyone contributing to write their commit messages a certain way. Ideally we aren't really bumping versions ever, so this might not matter.

I didn't realise that. I though ship.js would be a better option since it does releases manually compared to https://github.com/semantic-release/semantic-release which does the release automatically, which is exactly what we're trying to avoid here.

I agree with not enforcing conventional commits. I'll take a look to see how shipjs might work without using conventional commits.
